### ISSUE TITLE
readme 可以详细点嘛？

### ISSUE THREAD

**Issue by alsotang** [demohi/ivm#1]
比如写个 `usage` section 出来，再给个一句安装命令出来。

比如
## get start
1. install by one line: `$ curl github.com/demohi/ivm/xxxx.sh | sh`
2. `$ ivm install 1.0`
3. type iojs in your shell. `$ iojs`, and play it

这样新用户来到界面之后，就可以很顺利地成为 ivm 用户了。

然后，照抄一下 n 的 api 说明。比如 `n list` 可以列出所有版本啊之类的命令。

**Comment by alsotang** [comment]
如果这个工具可以率先实现 node.js 和 io.js 双重安装的话，那么可以去英文社区也发发帖

**Comment by desenmeng** [comment]
等下我更新一下用法再

ivm list 也是可以用的呀

**Comment by desenmeng** [comment]
感谢关注，已经更新了文档
目前 nvm 官方已经计划支持 iojs 了，这样travis等工具，也可以直接集成，所以 ivm 暂时不会增加 node 的支持了

**Comment by alsotang** [comment]
nvm 动作也好快啊

**Comment by desenmeng** [comment]
是呀  毕竟它也算是一个标准了  各大平台都用它
